package com.Team2_CDE_master.ProjectServer.crdt;

import java.util.ArrayList;

// this is the block-level CRDT
// it holds an ordered list of all blocks in the document (including deleted ones)
// each block contains its own CharCRDT for the characters inside it
// think of this as the document skeleton — it knows the order of all paragraphs
public class BlockCRDT {

    // all blocks in document order — including tombstoned ones
    public ArrayList<Block> allBlocks;

    public BlockCRDT() {
        allBlocks = new ArrayList<>();
    }

    // -----------------------------------------------------------------------
    // INSERT a block into the document
    // it goes right after its parent block
    // tie-breaker (concurrent inserts at same position): higher siteId goes first
    // same logic as CharCRDT.addChar — we keep it consistent across both layers
    // -----------------------------------------------------------------------
    public void addBlock(Block newBlock) {

        // find the position of the parent block
        int parentPos = -1;   // -1 means this block goes before everything (start of document)

        if (newBlock.getParentId() != null) {
            for (int i = 0; i < allBlocks.size(); i++) {
                if (allBlocks.get(i).getMyId().isSameAs(newBlock.getParentId())) {
                    parentPos = i;
                    break;
                }
            }
        }

        // figure out where exactly to insert — skip siblings with higher siteId
        int insertAt = parentPos + 1;

        while (insertAt < allBlocks.size()) {
            Block current = allBlocks.get(insertAt);

            // check if this block is a sibling (same parent = concurrent insert)
            boolean sameParent = false;
            if (newBlock.getParentId() == null && current.getParentId() == null) {
                sameParent = true;
            } else if (newBlock.getParentId() != null && current.getParentId() != null) {
                sameParent = current.getParentId().isSameAs(newBlock.getParentId());
            }

            if (sameParent) {
                // tie-breaker: higher siteId goes first (left/earlier in document)
                if (current.getMyId().siteId > newBlock.getMyId().siteId) {
                    insertAt++;   // skip this sibling, it wins
                } else {
                    break;        // our new block wins, insert here
                }
            } else {
                break;   // no more siblings
            }
        }

        allBlocks.add(insertAt, newBlock);
    }

    // -----------------------------------------------------------------------
    // DELETE a block — tombstone it, don't remove it from the list
    // -----------------------------------------------------------------------
    public void deleteBlock(BlockID targetId) {
        Block block = findBlock(targetId);
        if (block != null) {
            block.markDeleted();
        }
    }

    // -----------------------------------------------------------------------
    // SPLIT a block into two blocks at a given character position
    //
    // how it works:
    //   - the original block keeps all characters UP TO (but not including) splitIndex
    //   - a brand new block (newBlockId) gets all characters FROM splitIndex onward
    //   - the new block is inserted right after the original block
    //   - the new block's parentId = the original block's id
    //
    // splitIndex is the visible character index (counts only non-deleted chars)
    // newBlockId must be generated by the caller with their own siteId+counter
    // -----------------------------------------------------------------------
    public void splitBlock(BlockID targetId, int splitIndex, BlockID newBlockId) {

        Block original = findBlock(targetId);
        if (original == null || original.checkDeleted()) {
            System.out.println("splitBlock: block not found or already deleted — " + targetId);
            return;
        }

        // collect all visible (non-deleted) nodes from the original block
        ArrayList<CharNode> visibleNodes = new ArrayList<>();
        for (CharNode node : original.getContent().allNodes) {
            if (!node.checkDeleted()) {
                visibleNodes.add(node);
            }
        }

        // validate split index
        if (splitIndex <= 0 || splitIndex >= visibleNodes.size()) {
            System.out.println("splitBlock: splitIndex " + splitIndex + " is out of range for block " + targetId);
            return;
        }

        // create the new block — it will sit right after the original
        Block newBlock = new Block(newBlockId, targetId);

        // move characters from splitIndex onward into the new block
        // we tombstone them in the original and re-insert into the new block
        for (int i = splitIndex; i < visibleNodes.size(); i++) {
            CharNode node = visibleNodes.get(i);

            // tombstone in the original block
            node.markDeleted();

            // create a fresh copy for the new block
            // the first moved char has no parent (it starts the new block)
            // subsequent moved chars use the previous moved char's id as parent
            CharID newParentId = (i == splitIndex) ? null : visibleNodes.get(i - 1).getMyId();
            CharNode copy = new CharNode(node.getMyId(), newParentId, node.getMyChar());
            copy.setBold(node.checkBold());
            copy.setItalic(node.checkItalic());
            newBlock.getContent().addChar(copy);
        }

        // insert the new block right after the original in the document
        addBlock(newBlock);
    }

    // -----------------------------------------------------------------------
    // MERGE two consecutive blocks — second block's content goes into the first
    //
    // how it works:
    //   - find the last visible character of the first block (this becomes the parent
    //     for the first character we move from the second block)
    //   - move all visible characters from secondId into firstId, preserving order
    //   - tombstone the second block
    // -----------------------------------------------------------------------
    public void mergeBlocks(BlockID firstId, BlockID secondId) {

        Block first = findBlock(firstId);
        Block second = findBlock(secondId);

        if (first == null || second == null) {
            System.out.println("mergeBlocks: one or both blocks not found");
            return;
        }
        if (first.checkDeleted() || second.checkDeleted()) {
            System.out.println("mergeBlocks: one or both blocks already deleted");
            return;
        }

        // find the last visible node in the first block — it will become the parent
        // of the first node we bring over from the second block
        CharNode lastInFirst = null;
        for (CharNode node : first.getContent().allNodes) {
            if (!node.checkDeleted()) {
                lastInFirst = node;
            }
        }

        // collect all visible nodes from the second block in order
        ArrayList<CharNode> toMove = new ArrayList<>();
        for (CharNode node : second.getContent().allNodes) {
            if (!node.checkDeleted()) {
                toMove.add(node);
            }
        }

        // re-insert each node into the first block
        for (int i = 0; i < toMove.size(); i++) {
            CharNode original = toMove.get(i);

            // parent: first moved char hangs off the last char of the first block
            //         subsequent chars hang off the previous moved char
            CharID newParentId = (i == 0)
                    ? (lastInFirst != null ? lastInFirst.getMyId() : null)
                    : toMove.get(i - 1).getMyId();

            CharNode copy = new CharNode(original.getMyId(), newParentId, original.getMyChar());
            copy.setBold(original.checkBold());
            copy.setItalic(original.checkItalic());
            first.getContent().addChar(copy);
        }

        // tombstone the second block
        second.markDeleted();
    }

    // -----------------------------------------------------------------------
    // FIND a block by its id — returns null if not found
    // -----------------------------------------------------------------------
    public Block findBlock(BlockID targetId) {
        for (Block block : allBlocks) {
            if (block.getMyId().isSameAs(targetId)) {
                return block;
            }
        }
        return null;
    }

    // -----------------------------------------------------------------------
    // GET the full visible text of the entire document
    // skips deleted blocks and joins them with newlines
    // -----------------------------------------------------------------------
    public String getFullText() {
        StringBuilder sb = new StringBuilder();
        boolean firstVisible = true;
        for (Block block : allBlocks) {
            if (!block.checkDeleted()) {
                if (!firstVisible) sb.append("\n");
                sb.append(block.getText());
                firstVisible = false;
            }
        }
        return sb.toString();
    }

    // -----------------------------------------------------------------------
    // COUNT how many visible (non-deleted) blocks exist
    // -----------------------------------------------------------------------
    public int getBlockCount() {
        int count = 0;
        for (Block block : allBlocks) {
            if (!block.checkDeleted()) {
                count++;
            }
        }
        return count;
    }

    // -----------------------------------------------------------------------
    // DEBUG — print all blocks including tombstones
    // -----------------------------------------------------------------------
    public void printAll() {
        System.out.println("=== BlockCRDT (all blocks including deleted) ===");
        for (Block block : allBlocks) {
            System.out.println("  " + block.toString());
        }
        System.out.println("Full visible text:\n\"" + getFullText() + "\"");
        System.out.println("================================================");
    }
}